first_apps/first_apps/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('first_calendar.urls')),
]

first_apps/first_calendar/urls.py
from django.urls import path
from .import views

app_name = "first_calendar"
urlpatterns = [

    path('', views.OneMonthView.as_view(), name='month'),
    
    path('month/<int:year>/<int:month>/', views.OneMonthView.as_view(), name='month'),
    
    path('detail/<int:year>/<int:month>/<int:day>/', views.DetailWeekView.as_view(), name='detail'),
    
    path('category', views.CategoryView.as_view(), name="category"),
    
   
]

first_apps/first_calendar/models.py
from django.db import models
import datetime
from django.utils import timezone


class Category(models.Model):
    category_a = models.CharField(blank=True, null=True, max_length=100)
    category_b = models.CharField(blank=True, null=True, max_length=100)
    category_c = models.CharField(blank=True, null=True, max_length=100)
    category_d = models.CharField(blank=True, null=True, max_length=100)
    def __str__(self):
        return str(self.category_a)
    
class Money(models.Model):
    money_a = models.IntegerField(blank=True, null=True)
    money_b = models.IntegerField(blank=True, null=True)
    money_c = models.IntegerField(blank=True, null=True)
    money_d = models.IntegerField(blank=True, null=True)
    date = models.DateField('日付')
    
class Schedule(models.Model):
    
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.description

first_apps/first_calendar/forms.py
from django import formsfrom .models import Category,Moneyclass CategoryForm(forms.ModelForm):    class Meta:        model = Category        fields = ['category_a','category_b','category_c','category_d']        class MoneyForm(forms.ModelForm):    class Meta:        model = Money        fields = ['money_a','money_b','money_c','money_d']

first_apps/first_calendar/templates/first_calendar/category.html
<!DOCTYPE html><head>    <style>        </style></head><body><h1>好きなカテゴリ名を登録しよう</h1><form method="POST" enctype="multipart/form-data">{% csrf_token %}{{ form.as_p }}<button type="submit">登録する</button></form></body>

first_apps/first_calendar/templates/first_calendar/include/week.html
<!DOCTYPE html><head>    <style>    .now_day {      background-color: #eee;    }    .select_day {      background-color: #FF0066;    }    .containerrrr {      display: grid;      grid-template-columns:100px 100px 100px 100px 100px 100px 100px;    }    table.fixed {      table-layout: fixed;      width: 100%;    }    th {      width: 50px;      height: 10px;    }    td {      width: 50px;      height: 10px;    }        </style></head><body><a href="{% url 'first_calendar:category' %}">カテゴリ登録</a><a href="{% url 'first_calendar:month' %}">月間へ戻る</a><form method="POST" enctype="multipart/form-data">{% csrf_token %}<p>{{ categorys.0 }} : {{ form.money_a }}</p><p>{{ categorys.1 }} : {{ form.money_b }}</p><p>{{ categorys.2 }} : {{ form.money_c }}</p><p>{{ categorys.3 }} : {{ form.money_d }}</p><button type="submit">登録する</button></form><br><table class="fixed" border="1">    <tr class="container">    {% for w in week_names %}        <th>{{ w }}</th>    {% endfor %}    </tr>    <tr class="container">    {% for times in week_schedules %}        {% if now.day == times.day %}        <td class="now_day">        {% elif select_day.day == times.day %}        <td class="select_day">        {% else %}        <td>        {% endif %}           {{ times.month }}/{{ times.day }}        </td>    {% endfor %}    </tr>    <tr class="container">    {% for schedules in week_schedules.values %}        <td>        {% for schedule in schedules  %}            <p>{{ categorys.0 }}:{{ schedule.money_a }}</p>            <p>{{ categorys.1 }}:{{ schedule.money_b }}</p>            <p>{{ categorys.2 }}:{{ schedule.money_c }}</p>            <p>{{ categorys.3 }}:{{ schedule.money_d }}</p>                  {% endfor %}        </td>    {% endfor %}    </tr></table>{% for k,v in graph.items %}    <img src="data:image/svg+xml;base64,{{v}}" />{% endfor %}

first_apps/first_calendar/templates/first_calendar/index.html
<!DOCTYPE html><head>    <style>    .now_day {background-color: #eee}    .containerrrr {display: grid;                grid-template-columns:100px 100px 100px 100px 100px 100px 100px;                }    table.fixed {table-layout: fixed;                 width: 100%}    th {width: 50px;           height: 10px}    td {width: 50px;           height: 10px}        </style></head><body><a href="{% url 'first_calendar:category' %}">カテゴリ登録</a><form method="POST" enctype="multipart/form-data">{% csrf_token %}<p>{{ categorys.0 }} : {{ form.money_a }}</p><p>{{ categorys.1 }} : {{ form.money_b }}</p><p>{{ categorys.2 }} : {{ form.money_c }}</p><p>{{ categorys.3 }} : {{ form.money_d }}</p><button type="submit">登録する</button></form><img src="data:image/png;base64,{{ chart | safe }}">{% include 'first_calendar/include/week.html' %}<h1>問題点</<h1><h2>matplotlibのHTML出力</<h2><h2>pkを用いてmonthからweek表示</h2><h2>month = datetime.date.today().replace(day=1)</h2>

first_apps/first_calendar/templates/first_calendar/month.html
<!DOCTYPE html><head>    <style>    .now_day {      background-color: #eee    }    .containerrrr {      display: grid;      grid-template-columns:100px 100px 100px 100px 100px 100px 100px;    }    table.fixed {      table-layout: fixed;      width: 100%    }    th {      width: 50px;      height: 10px;    }    td {      width: 50px;      height: 50px;    }        </style></head><body><h1>month</h1><a href={% url 'first_calendar:month' month_previous.year month_previous.month %}>先月 {{month_previous.month}}月</a><a href={% url 'first_calendar:month' month_next.year month_next.month %}>来月 {{month_next.month}}月</a><table class="fixed" border="1">    <tr class="container">    {% for w in week_names %}        <th>{{ w }}</th>    {% endfor %}    </tr>            <tr class="container">        {% for week in month_day_schedules %}        <tr>            {% for day in week.items %}                                     {% if now == day.0 %}                <td class="now_day">            {% else %}                <td>            {% endif %}           <a href={% url 'first_calendar:detail' day.0.year day.0.month day.0.day %}>{{ day.0.month }}/{{ day.0.day }}</a>            <p>{{day.1.0.money_a|truncatechars:1}}</p>                </td>            {% endfor %}        </tr>       {% endfor %}    </tr>   </table></body>

first_apps/first_calendar/templates/first_calendar/month_week.html
<!DOCTYPE html><head>    <style>    .now_day {background-color: #eee}    .containerrrr {display: grid;                grid-template-columns:100px 100px 100px 100px 100px 100px 100px;                }    table.fixed {table-layout: fixed;                 width: 100%}    th {width: 50px;           height: 10px}    td {width: 50px;           height: 10px}        </style></head><body>{% for week in month_day_schedules %}{% for day in week.items %}<h3>{{day.1.0.pk}}</h3>{% endfor %}{% endfor %}<h1>month</h1><table class="fixed" border="1">    <tr class="container">    {% for w in week_names %}        <th>{{ w }}</th>    {% endfor %}    </tr>    <tr class="container">        {% for week in month_day_schedules %}        <tr>            {% for day in week.items %}            {% if now == day.0 %}               <td class="now_day">            {% else %}                <td>            {% endif %}             <a href={% url 'first_calendar:detail' day.1.0 %}>{{ day.0.month }}/{{ day.0.day }}</a>            <p>{{day.1.0}}</p>                </td>            {% endfor %}        </tr>       {% endfor %}    </tr>   </table>{% for serial in month_serial %}{% for i in serial %}<p>{{i}}</p>{% endfor %}{% endfor %}</body>

first_apps/first_calendar/templates/first_calendar/test.html
<!DOCTYPE html><html><head>	<meta charset="utf-8">	<title></title></head><body><h1>test</h1>    	<img src="data:image/svg+xml;base64,{{graph}}" /></body></html>